server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: testpass.keystore
      keyStorePassword: testpass
      validateCerts: false
      validatePeers: false